commonLabels:
  org: admin-portal-test

resources:
  - deployment.yaml
  - service.yaml
  - proxy-service.yaml

secretGenerator:
  - name: admin-secret
    type: Opaque
    envCommand: "sops -d secrets/admin-secret.enc.env"

imageTags:
  - name: medineshkatwal/forest-admin-portal